FROM golang:latest AS builder

WORKDIR /app

COPY shared/ ./shared/
COPY services/posts/ ./services/posts/

WORKDIR /app/services/posts   

RUN go mod download

RUN CGO_ENABLED=0 go build -o post_grpc ./cmd/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/services/posts/post_grpc .

EXPOSE 8080

CMD ["./post_grpc"]