FROM golang:latest AS builder

WORKDIR /app

COPY shared/ ./shared/
COPY services/comments/ ./services/comments/

WORKDIR /app/services/comments

RUN go mod download

RUN CGO_ENABLED=0 go build -o comment_grpc ./cmd/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/services/comments/comment_grpc .

EXPOSE 8080

CMD ["./comment_grpc"]