FROM golang:1.24 AS builder

WORKDIR /app

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 go build -o gateway ./cmd/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/gateway .
COPY --from=builder /app/api_docs.yaml ./api_docs.yaml

EXPOSE 8080

CMD ["./gateway"]