FROM golang:latest AS builder

WORKDIR /app

COPY shared/ ./shared/
COPY gateway/ ./gateway/

WORKDIR /app/gateway

RUN go mod download

RUN CGO_ENABLED=0 go build -o gateway ./cmd/main.go

FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/gateway/gateway .
COPY --from=builder /app/gateway/api_docs.yaml ./api_docs.yaml

EXPOSE 8080

CMD ["./gateway"]