// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"voidspace/users/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFollowRepository creates a new instance of MockFollowRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFollowRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFollowRepository {
	mock := &MockFollowRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFollowRepository is an autogenerated mock type for the FollowRepository type
type MockFollowRepository struct {
	mock.Mock
}

type MockFollowRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFollowRepository) EXPECT() *MockFollowRepository_Expecter {
	return &MockFollowRepository_Expecter{mock: &_m.Mock}
}

// Follow provides a mock function for the type MockFollowRepository
func (_mock *MockFollowRepository) Follow(ctx context.Context, updates *domain.Follow) error {
	ret := _mock.Called(ctx, updates)

	if len(ret) == 0 {
		panic("no return value specified for Follow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Follow) error); ok {
		r0 = returnFunc(ctx, updates)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFollowRepository_Follow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Follow'
type MockFollowRepository_Follow_Call struct {
	*mock.Call
}

// Follow is a helper method to define mock.On call
//   - ctx context.Context
//   - updates *domain.Follow
func (_e *MockFollowRepository_Expecter) Follow(ctx interface{}, updates interface{}) *MockFollowRepository_Follow_Call {
	return &MockFollowRepository_Follow_Call{Call: _e.mock.On("Follow", ctx, updates)}
}

func (_c *MockFollowRepository_Follow_Call) Run(run func(ctx context.Context, updates *domain.Follow)) *MockFollowRepository_Follow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Follow
		if args[1] != nil {
			arg1 = args[1].(*domain.Follow)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFollowRepository_Follow_Call) Return(err error) *MockFollowRepository_Follow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFollowRepository_Follow_Call) RunAndReturn(run func(ctx context.Context, updates *domain.Follow) error) *MockFollowRepository_Follow_Call {
	_c.Call.Return(run)
	return _c
}

// Unfollow provides a mock function for the type MockFollowRepository
func (_mock *MockFollowRepository) Unfollow(ctx context.Context, updates *domain.Follow) error {
	ret := _mock.Called(ctx, updates)

	if len(ret) == 0 {
		panic("no return value specified for Unfollow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Follow) error); ok {
		r0 = returnFunc(ctx, updates)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFollowRepository_Unfollow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unfollow'
type MockFollowRepository_Unfollow_Call struct {
	*mock.Call
}

// Unfollow is a helper method to define mock.On call
//   - ctx context.Context
//   - updates *domain.Follow
func (_e *MockFollowRepository_Expecter) Unfollow(ctx interface{}, updates interface{}) *MockFollowRepository_Unfollow_Call {
	return &MockFollowRepository_Unfollow_Call{Call: _e.mock.On("Unfollow", ctx, updates)}
}

func (_c *MockFollowRepository_Unfollow_Call) Run(run func(ctx context.Context, updates *domain.Follow)) *MockFollowRepository_Unfollow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Follow
		if args[1] != nil {
			arg1 = args[1].(*domain.Follow)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFollowRepository_Unfollow_Call) Return(err error) *MockFollowRepository_Unfollow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFollowRepository_Unfollow_Call) RunAndReturn(run func(ctx context.Context, updates *domain.Follow) error) *MockFollowRepository_Unfollow_Call {
	_c.Call.Return(run)
	return _c
}
