"""Add username field to posts

Revision ID: 93ffc90a5146
Revises: cd7afd694a03
Create Date: 2025-07-17 02:19:29.639522

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "93ffc90a5146"
down_revision: Union[str, Sequence[str], None] = "cd7afd694a03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("post_author", sa.String()))
    op.execute("UPDATE posts SET post_author = id WHERE post_author IS NULL")
    op.drop_column("posts", "post_author_id")
    op.alter_column('posts', 'post_author', nullable=False)
    op.add_column("posts_likes", sa.Column("username", sa.String()))
    op.drop_column("posts_likes", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "posts_likes",
        sa.Column("user_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("posts_likes", "username")
    op.add_column(
        "posts",
        sa.Column("post_author_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("posts", "post_author")
    # ### end Alembic commands ###
