"""new initial

Revision ID: cd7afd694a03
Revises: 
Create Date: 2025-07-16 01:15:42.821464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7afd694a03'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('post_content', sa.String(), nullable=False),
    sa.Column('post_author_id', sa.String(), nullable=False),
    sa.Column('post_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('post_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('post_image', sa.JSON(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts_likes',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('post_id', sa.String(), nullable=False),
    sa.Column('like_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_likes')
    op.drop_table('posts')
    # ### end Alembic commands ###
