"""Add index

Revision ID: e5f5ea28d3db
Revises: 93ffc90a5146
Create Date: 2025-07-17 02:31:42.131781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f5ea28d3db'
down_revision: Union[str, Sequence[str], None] = '93ffc90a5146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_posts_post_author'), 'posts', ['post_author'], unique=False)
    op.create_index(op.f('ix_posts_post_created_at'), 'posts', ['post_created_at'], unique=False)
    op.alter_column('posts_likes', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts_likes', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_posts_post_created_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_post_author'), table_name='posts')
    # ### end Alembic commands ###
