ALTER TABLE users
ADD COLUMN new_id CHAR(36) NOT NULL DEFAULT (UUID());
UPDATE users SET new_id = UUID();
ALTER TABLE users DROP PRIMARY KEY;
ALTER TABLE users DROP COLUMN id;
ALTER TABLE users CHANGE COLUMN new_id id CHAR(36) NOT NULL;
ALTER TABLE users ADD PRIMARY KEY (id);